---

- name: Install Kubernetes cluster via RKE on EC2 instances
  hosts: tag_group_k8s_rke
  collections:
    - amazon.aws
    - community.aws.ec2_instance_facts

  vars:
    ansible_aws_region: "us-west-2"
    ansible_aws_security_group: "Filbert_Estates_ssh"
    ansible_aws_key_name: "alklein_us-west"
    ansible_aws_instance_group: "k8s-rke"
    ansible_instance_status: stopped
    ansible_aws_activity: build
    ansible_ec2_debug: false

  roles:
  - role: ansible-role-rke-k8s
    vars:
      ansible_ec2_packages:
      - docker
