---

- name: Install Kubernetes cluster via RKE on EC2 instances
  hosts: tag_group_rke_k8s
  collections:
    - amazon.aws
    - community.aws.ec2_instance_facts

  vars:
    ansible_ec2_instance_user: ec2-user
    ansible_aws_instance_group: "rke-k8s"
    ansible_ec2_debug: true


  roles:
  - role: ansible-role-rke-k8s
    vars:
      ansible_add_ec2_packages:
#      - apt-transport-https
      - ca-certificates
      - curl
#      - gnupg-agent
#      - software-properties-common

      ansible_docker_ec2_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

      ansible_remove_ec2_packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
