---

- name: Install Kubernetes cluster via RKE on EC2 instances
  hosts: 
  collections:
    - amazon.aws
    - community.aws.ec2_instance_facts

  vars:
    ansible_aws_instance_type: "t2.micro"
    ansible_aws_image_name:  "ami-01fee56b22f308154"
    ansible_aws_region: "us-west-2"
    ansible_aws_security_group: "Filbert_Estates_ssh"
    ansible_aws_key_name: "alklein_us-west"
    ansible_aws_instance_group: "k8s-rke"
    ansible_instance_status: stopped
    ansible_aws_activity: build
    ansible_ec2_debug: false
    ansible_ec2_packages:
      - docker-ce

  roles:
  - role: ansible-role-ec2-instances
    hosts: localhost
    vars:
    ansible_instance_count: 7
    when: ansible_aws_activity == "build"
