---

# Install specified packages on EC2 instances

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
    use_backend: yum
  loop: "{{ ansible_ec2_packages }}"
  become: true
  register: __install

- name: Debug install
  debug:
    msg: "{{ __install }}"
  when: ansible_ec2_debug == true

- name: enable and start docker
  sysvinit:
    name: docker
    state: started
    enabled: true
  become: true

- name: Validate docer with ps
  block:

  - name: Docker ps
    shell:
      cmd: 'docker ps -a'
    become: true
    register: __docker_ps

  - name: Return docker ps output
    debug:
      msg: "{{ __docker_ps.stdout }}"
  
  when: ansible_ec2_debug == true

- name: Create /etc/systemd/docker.service.d directory
  file:
    path: /etc/systemd/docker.service.d
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Copy mount_flags.conf to /etc/systemd/docker.service.d/
  copy:
    src: files/mount_flags.conf
    dest: /etc/systemd/docker.service.d/mount_flags.conf
    mode: '0644'
    owner: root
    group: root
  become: true

- name: Fix /var/lib shared error
  shell: 'mount --make-rshared /'
  become: true

- name: Enable sshd TCPForwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#AllowTcpForwarding yes'
    lineinfile: 'AllowTcpForwarding yes'
  become: true
